name: Build Assets.json

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Setup Node.js & Build Assets.json
      uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: 'npm'
    - run: npm i
    - run: npm run build
    - run: | 
          git config --global user.name 'Kellojo'
          git config --global user.email 'kellojo@users.noreply.github.com'
          git commit -am "Automated assets.json update"
          git push
          
          
    - name: Push Assets.json to GitHub Pages Project
      uses: dmnemec/copy_file_to_another_repo_action@main
      env:
        API_TOKEN_GITHUB: ${{ secrets.MESH_KIT_PUSH_PAT }}
      with:
        source_file: 'assets.json'
        destination_repo: 'Kellojo/Mesh-Kit'
        destination_folder: 'src/assets/'
        user_email: 'kellojo@users.noreply.github.com'
        user_name: 'Kellojo'
        commit_message: 'Updated assets.json via automated workflow'
